[package]
name = "hello"
version = "0.1.0"
edition = "2021"
workspace = ".."
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.russenger]
path = "../.."

[dependencies]
actix-web = "^4"
rusql-alchemy = "0.1.0"
